version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g aws-cdk
      - npm ci
  build:
    commands:
      - npm run build
      - npx cdk synth ServiceStack --output cdk.out

artifacts:
  base-directory: cdk.out
  files:
    - ServiceStack.template.json
